anaxago_core_project:
    resource: "@AnaxagoCoreBundle/Controller/ProjectController.php"
    type:     annotation

anaxago_core_project_user:
    resource: "@AnaxagoCoreBundle/Controller/ProjectUserController.php"
    type:     annotation

anaxago_core:
    resource: "@AnaxagoCoreBundle/Resources/config/routing.yml"
    prefix:   /

login:
    path: /login
    defaults: { _controller: AnaxagoCoreBundle:Security:login }

logout:
    path: /logout

anaxago_core_registration:
    path: /register
    defaults: { _controller: AnaxagoCoreBundle:Security:registration }